name: Build and Test 

on: 
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: string
      runs-on: 
        description: 'Runs on'
        required: true
        type: string

jobs:
  Build:
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Download Build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-${{inputs.version}}

      - name: Unzip Build artifact
        run: |
          tar -xvf build-${{inputs.version}}.zip

      - name: Write .env
        env:
          DOTENV: '${{ vars.DOTENV }}'
        run: |
          echo -e "$DOTENV" > ./.env
          sed -i 's/\r//g' ./.env
          
      - name: Run start
        run: |
          npm install
          npm run start 