name: Workflow A

on:
  push:
    branches:
      - master

jobs:
  Semantic-Versioning:
    uses: ./.github/workflows/sem-ver.yaml
    
  Build:
    needs: 
      - Semantic-Versioning
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.semantic-versioning.outputs.version }}

  Test:
    needs: 
      - Semantic-Versioning
      - Build
    uses: ./.github/workflows/test.yaml
    with:
        version: ${{ needs.semantic-versioning.outputs.version }}

  Deploy:
    needs: 
      - Semantic-Versioning
      - Build
      - Test
    uses: ./.github/workflows/deploy.yaml
    with:
        version: ${{ needs.semantic-versioning.outputs.version }}
        environment: production
        runs-on: ubuntu-latest