name: Workflow A

on:
  push:
    branches:
      - master

jobs:
  Semantic-Versioning:
    uses: ./.github/workflows/sem-ver.yaml
    
  Build:
    needs:
      - Semantic-Versioning
    runs-on: ubuntu-latest
    steps:
      - name: Build Node App
        uses: ./.github/workflows/build.yaml
        with:
          version: ${{ needs.semantic-versioning.outputs.version }}

  Test:
    needs: 
      - Semantic-Versioning
      - Build
    runs-on: ubuntu-latest
    steps:
      - name: Test Node App
        uses: ./.github/workflows/test.yaml
        with:
          version: ${{ needs.semantic-versioning.outputs.version }}
