name: sem-ver
on:
  push:
    branches:
      - develop
      - release
      - master

jobs:
  Check_Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Previous Version
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0

      # 현재 브랜치를 확인하여 작업 분기
      - name: Check Current Branch
        id: current-branch
        run: echo "Current branch is ${{ github.ref }}"
      
      - name: print current branch
        run: echo ${{ steps.current-branch.outputs }}

      # develop 브랜치인 경우에만 실행
      - name: Do Something on Develop
        if: ${{ steps.current-branch.outputs.current-branch == 'refs/heads/develop' }}
        run: |
          echo "This is the develop branch. Do something here."

      # release 브랜치인 경우에만 실행
      - name: Do Something on Release
        if: ${{ steps.current-branch.outputs.current-branch == 'refs/heads/release' }}
        run: |
          echo "This is the release branch. Do something here."

      # master 브랜치인 경우에만 실행
      - name: Do Something on Master
        if: ${{ steps.current-branch.outputs.current-branch == 'refs/heads/master' }}
        run: |
          echo "This is the master branch. Do something here."
